In [1]:
import pandas  as pd
import re
import numpy as np

In [2]:
data=pd.read_csv("C:/Users/97155/Downloads/potential-talents - Aspiring human resources - seeking human resources.csv")

In [3]:
data

id                                          job_title  \
0      1  2019 C.T. Bauer College of Business Graduate (...   
1      2  Native English Teacher at EPIK (English Progra...   
2      3              Aspiring Human Resources Professional   
3      4             People Development Coordinator at Ryan   
4      5    Advisory Board Member at Celal Bayar University   
..   ...                                                ...   
99   100  Aspiring Human Resources Manager | Graduating ...   
100  101              Human Resources Generalist at Loparex   
101  102   Business Intelligence and Analytics at Travelers   
102  103                     Always set them up for Success   
103  104   Director Of Administration at Excellence Logging   

                                location connection  fit  
0                         Houston, Texas         85  NaN  
1                                 Kanada      500+   NaN  
2    Raleigh-Durham, North Carolina Area         44  NaN  
3                          Denton, Texas      500+   NaN  
4                         İzmir, Türkiye      500+   NaN  
..                                   ...        ...  ...  
99              Cape Girardeau, Missouri        103  NaN  
100  Raleigh-Durham, North Carolina Area      500+   NaN  
101           Greater New York City Area         49  NaN  
102             Greater Los Angeles Area      500+   NaN  
103                          Katy, Texas      500+   NaN  

[104 rows x 5 columns]

In [4]:
data["job_title"][:4]

0    2019 C.T. Bauer College of Business Graduate (...
1    Native English Teacher at EPIK (English Progra...
2                Aspiring Human Resources Professional
3               People Development Coordinator at Ryan
Name: job_title, dtype: object

In [5]:
import re
keywords = ["Human Resources"]

pattern = '|'.join(keywords)

data.loc[data["job_title"].str.contains(pattern, case=False, regex=True), "fit"] = 1

data=data.fillna(0)

In [6]:
data["fit"].value_counts()

1.0    60
0.0    44
Name: fit, dtype: int64

# Bag of Word

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

keywords = ["Human Resources", "Aspiring human resources", "seeking human resources"]
v = CountVectorizer()
key = v.fit_transform(keywords).toarray()
key

array([[0, 1, 1, 0],
       [1, 1, 1, 0],
       [0, 1, 1, 1]], dtype=int64)

In [8]:
v.vocabulary_

{'human': 1, 'resources': 2, 'aspiring': 0, 'seeking': 3}

In [9]:
v.get_feature_names_out()

array(['aspiring', 'human', 'resources', 'seeking'], dtype=object)

In [10]:
 job_title= data["job_title"]

In [12]:
v.vocabulary_

{'human': 1, 'resources': 2, 'aspiring': 0, 'seeking': 3}

In [13]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
clf=Pipeline([
    ("vectorization", CountVectorizer()),
    ("np", MultinomialNB())
])

# TF-IDF

IDF(inverse document frequancy) = log(Total number of documents/number of documents term t present in )

TF(term frequancy) = (Total number of time term t is present in doc A / Total number of tokens in doc A)

TF-IDF = TF * IDF

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
job_title= data["job_title"]

tf=TfidfVectorizer()
job_title_tf =tf.fit_transform(job_title)

In [16]:
dir(tf)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_params',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_tfidf',
 '_validate_data',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 

In [17]:
tf.vocabulary_

{'2019': 0,
 'bauer': 23,
 'college': 38,
 'of': 127,
 'business': 32,
 'graduate': 74,
 'magna': 114,
 'cum': 46,
 'laude': 103,
 'and': 15,
 'aspiring': 18,
 'human': 84,
 'resources': 155,
 'professional': 146,
 'native': 124,
 'english': 59,
 'teacher': 180,
 'at': 20,
 'epik': 63,
 'program': 148,
 'in': 87,
 'korea': 101,
 'people': 140,
 'development': 50,
 'coordinator': 43,
 'ryan': 159,
 'advisory': 9,
 'board': 29,
 'member': 121,
 'celal': 34,
 'bayar': 24,
 'university': 189,
 'specialist': 169,
 'student': 174,
 'humber': 85,
 'generalist': 71,
 'hr': 82,
 'senior': 164,
 'seeking': 163,
 'hris': 83,
 'positions': 144,
 'chapman': 36,
 'svp': 177,
 'chro': 37,
 'marketing': 118,
 'communications': 39,
 'csr': 45,
 'officer': 129,
 'engie': 57,
 'houston': 81,
 'the': 182,
 'woodlands': 197,
 'energy': 55,
 'gphr': 73,
 'sphr': 170,
 'intercontinental': 93,
 'buckhead': 31,
 'atlanta': 21,
 'management': 116,
 'an': 12,
 'internship': 95,
 'opportunities': 132,
 'experienc

In [18]:
all_features = tf.get_feature_names_out()
all_features

array(['2019', '2020', '2621', '408', '709', 'about', 'administration',
       'administrative', 'admissions', 'advisory', 'always', 'america',
       'an', 'analyst', 'analytics', 'and', 'army', 'arts', 'aspiring',
       'assistant', 'at', 'atlanta', 'bachelor', 'bauer', 'bayar',
       'beach', 'benefits', 'beneteau', 'biology', 'board', 'brand',
       'buckhead', 'business', 'care', 'celal', 'center', 'chapman',
       'chro', 'college', 'communications', 'community', 'compensation',
       'conflict', 'coordinator', 'create', 'csr', 'cum', 'customer',
       'data', 'delphi', 'development', 'director', 'employment',
       'endemol', 'energetic', 'energy', 'engaging', 'engie', 'engineer',
       'english', 'entry', 'environment', 'environmental', 'epik',
       'excellence', 'executive', 'experienced', 'ey', 'focused', 'for',
       'from', 'generalist', 'gis', 'gphr', 'graduate', 'graduating',
       'groupe', 'guard', 'hardware', 'heil', 'helping', 'houston', 'hr',
       'hris

In [19]:
for word in all_features:
    indx = tf.vocabulary_.get(word)
    print(f"{word} {tf.idf_[indx]}")

2019 3.5745188084776873
2020 4.960813169597579
2621 4.960813169597579
408 4.960813169597579
709 4.960813169597579
about 4.960813169597579
administration 4.960813169597579
administrative 4.960813169597579
admissions 4.960813169597579
advisory 4.044522437723423
always 4.960813169597579
america 4.555348061489413
an 3.8622008809294686
analyst 4.960813169597579
analytics 4.960813169597579
and 2.3217558399823197
army 4.960813169597579
arts 4.960813169597579
aspiring 2.070441411701413
assistant 4.960813169597579
at 1.8253189536684284
atlanta 4.044522437723423
bachelor 4.960813169597579
bauer 3.5745188084776873
bayar 4.044522437723423
beach 4.960813169597579
benefits 4.960813169597579
beneteau 4.960813169597579
biology 4.960813169597579
board 4.044522437723423
brand 4.960813169597579
buckhead 4.044522437723423
business 3.169053700369523
care 4.960813169597579
celal 4.044522437723423
center 4.960813169597579
chapman 4.044522437723423
chro 4.044522437723423
college 2.9459101490553135
communicati

In [20]:
job_title_tf.toarray()[:2]

array([[0.31701856, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.20591294, 0.        , 0.        , 0.18362426, 0.        ,
        0.        , 0.        , 0.        , 0.31701856, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.28105849, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.26126823, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.31701856, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [21]:
seed=1
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data.job_title, data.fit, test_size=0.20, random_state=seed)

In [22]:
from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.naive_bayes import MultinomialNB
clf = Pipeline([
    ("vect", TfidfVectorizer()),
    ("model",RandomForestClassifier())
])

In [23]:
clf.fit(x_train,y_train)
y_pre = clf.predict(x_test)
print(classification_report(y_test,y_pre))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        10
         1.0       1.00      1.00      1.00        11

    accuracy                           1.00        21
   macro avg       1.00      1.00      1.00        21
weighted avg       1.00      1.00      1.00        21



In [24]:
y_test[:7]

96    1.0
35    1.0
81    1.0
59    1.0
38    1.0
39    1.0
53    0.0
Name: fit, dtype: float64

In [25]:
y_pre[:7]

array([1., 1., 1., 1., 1., 1., 0.])

In [26]:
ahmad = ["human", "engineer human"]


In [27]:
y_pre = clf.predict(ahmad)

In [28]:
y_pre

array([1., 0.])

# Word2vac

In [29]:
import gensim

In [30]:
preprocessed_titles = job_title.apply(gensim.utils.simple_preprocess)
preprocessed_titles

0      [bauer, college, of, business, graduate, magna...
1      [native, english, teacher, at, epik, english, ...
2             [aspiring, human, resources, professional]
3           [people, development, coordinator, at, ryan]
4      [advisory, board, member, at, celal, bayar, un...
                             ...                        
99     [aspiring, human, resources, manager, graduati...
100          [human, resources, generalist, at, loparex]
101    [business, intelligence, and, analytics, at, t...
102                [always, set, them, up, for, success]
103    [director, of, administration, at, excellence,...
Name: job_title, Length: 104, dtype: object

In [31]:
model = gensim.models.Word2Vec(window=5, min_count=2, workers=4)

In [32]:
model.build_vocab(preprocessed_titles,progress_per=1000)

In [33]:
model.epochs

5

In [34]:
model.train(preprocessed_titles,total_examples=model.corpus_count, epochs=5)

(992, 3775)

In [35]:
model.save("woed2vec")

In [36]:
model.wv.most_similar("resources")

[('systems', 0.3124673366546631),
 ('coordinator', 0.24419854581356049),
 ('college', 0.22357207536697388),
 ('staffing', 0.2108517736196518),
 ('csr', 0.20866097509860992),
 ('gphr', 0.20733292400836945),
 ('hr', 0.19480784237384796),
 ('program', 0.18411137163639069),
 ('native', 0.1830090433359146),
 ('officer', 0.1728605031967163)]

# Word empedding 

In [37]:
import spacy
nlp = spacy.load("en_core_web_md")

In [38]:
keys = nlp("Aspiring Human Resources")

for token in keys:
    print(token.text, "vectoer:", token.has_vector, "OOV:", token.is_oov) #oov: out of vocabulary

Aspiring vectoer: True OOV: False
Human vectoer: True OOV: False
Resources vectoer: True OOV: False


In [96]:
for token in tokens:
    print(f'{token.text}<->{keys.text}',token.similarity(keys))

2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional<->Human Resources HR 0.5378415872200849
Native English Teacher at EPIK (English Program in Korea)<->Human Resources HR 0.32015701373602984
Aspiring Human Resources Professional<->Human Resources HR 0.7653773370353237
People Development Coordinator at Ryan<->Human Resources HR 0.3751102920600393
Advisory Board Member at Celal Bayar University<->Human Resources HR 0.3525901571905871
Aspiring Human Resources Specialist<->Human Resources HR 0.7752092040645733
Student at Humber College and Aspiring Human Resources Generalist<->Human Resources HR 0.5487829372662772
HR Senior Specialist<->Human Resources HR 0.8586620633857759
Student at Humber College and Aspiring Human Resources Generalist<->Human Resources HR 0.5487829372662772
Seeking Human Resources HRIS and Generalist Positions<->Human Resources HR 0.8580989050424955
Student at Chapman University<->Human Resources HR 0.284794499884034

In [52]:
job_title= data["job_title"]

In [54]:
tokens = []
for i in range(job_title.shape[0]):
    arr = nlp(job_title.iloc[i])
    tokens.append(arr)


In [55]:
similarity=[]
for i in range(job_title.shape[0]):
    arr= tokens[i].similarity(keys)
    similarity.append(arr)

In [ ]:
for token in tokens:
    print(f'{token.text} <-> {keys.text}', token.similarity(keys))

# cosine similarity

In [57]:
from sklearn.metrics.pairwise import cosine_similarity ,cosine_distances

In [58]:
keys = nlp("Human Resources HR")

In [59]:
cosin_sim = []
for i in range(job_title.shape[0]):
    sim = cosine_similarity(tokens[i].vector.reshape(1, -1), keys.vector.reshape(1, -1))
    cosin_sim.append(sim)


In [60]:
data["similarity"]= cosin_sim

In [61]:
data

id                                          job_title  \
0      1  2019 C.T. Bauer College of Business Graduate (...   
1      2  Native English Teacher at EPIK (English Progra...   
2      3              Aspiring Human Resources Professional   
3      4             People Development Coordinator at Ryan   
4      5    Advisory Board Member at Celal Bayar University   
..   ...                                                ...   
99   100  Aspiring Human Resources Manager | Graduating ...   
100  101              Human Resources Generalist at Loparex   
101  102   Business Intelligence and Analytics at Travelers   
102  103                     Always set them up for Success   
103  104   Director Of Administration at Excellence Logging   

                                location connection  fit  \
0                         Houston, Texas         85  1.0   
1                                 Kanada      500+   0.0   
2    Raleigh-Durham, North Carolina Area         44  1.0   
3                          Denton, Texas      500+   0.0   
4                         İzmir, Türkiye      500+   0.0   
..                                   ...        ...  ...   
99              Cape Girardeau, Missouri        103  1.0   
100  Raleigh-Durham, North Carolina Area      500+   1.0   
101           Greater New York City Area         49  0.0   
102             Greater Los Angeles Area      500+   0.0   
103                          Katy, Texas      500+   0.0   

                                         job_title_vec      similarity  
0    [-1.8883824, -3.1197147, 1.8757412, 1.2693827,...   [[0.5378416]]  
1    [-2.3733625, -3.954522, 2.3252928, 1.4753345, ...  [[0.32015702]]  
2    [-1.121565, -1.5824499, 0.89269996, -0.6570975...   [[0.7653773]]  
3    [-0.414018, -2.3088799, -1.2606045, 0.751188, ...  [[0.37511033]]  
4    [-1.6404866, -1.4406859, 0.8937308, 0.25696, 0...   [[0.3525902]]  
..                                                 ...             ...  
99   [0.19153328, -3.136853, 2.659192, 1.4459857, 2...  [[0.54647344]]  
100  [-1.0762001, -2.8991761, -1.1778839, 0.2094180...   [[0.5126755]]  
101  [-0.02945008, -2.4679286, -1.6339632, 1.630481...   [[0.4500219]]  
102  [-1.805175, 0.41841665, -3.1739433, 3.0301316,...  [[0.12133815]]  
103  [0.17022501, -4.6638336, 0.57790506, 2.1279285...  [[0.41380605]]  

[104 rows x 7 columns]

In [62]:
data["job_title_vec"] = data["job_title"].apply(lambda x: nlp(x).vector)

In [63]:
data['fit'] = data['similarity'].apply(lambda x: 1 if x >= 0.5 else 0)

In [64]:
features =data[['similarity',"job_title_vec"]]

In [65]:
target =data["fit"]

In [66]:
x_train,x_test,y_train,y_test = train_test_split(features, target, test_size=0.20, random_state=seed)

In [67]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

In [68]:
x_train_2d= np.stack(x_train["job_title_vec"])
x_test_2d=np.stack(x_test["job_title_vec"])

In [69]:
model.fit(x_train_2d,y_train)

RandomForestClassifier()

In [70]:
y_pre=model.predict(x_test_2d)

In [71]:
from sklearn.metrics import classification_report
clf_rep= classification_report(y_pre,y_test)

In [72]:
print(clf_rep)

              precision    recall  f1-score   support

           0       1.00      0.90      0.95        10
           1       0.92      1.00      0.96        11

    accuracy                           0.95        21
   macro avg       0.96      0.95      0.95        21
weighted avg       0.96      0.95      0.95        21



# word vectors in gensim

In [73]:
import gensim.downloader as api

In [80]:
data=pd.read_csv("C:/Users/97155/Downloads/potential-talents - Aspiring human resources - seeking human resources.csv")

In [74]:
wv = api.load("word2vec-google-news-300")

In [78]:

nlp = spacy.load("en_core_web_md")
def preprocess_and_vectorize(text):
    doc = nlp(text)
    filtered = []
    for token in doc:
        if token.is_punct or token.is_stop:
            continue
        filtered.append(token.lemma_)
    
    vectors = [nlp(word).vector for word in filtered]
    if vectors:
        mean_vector = np.mean(vectors, axis=0)
    else:
        mean_vector = np.zeros(nlp.vocab.vectors.shape[1])
    
    return mean_vector

In [132]:
doc = nlp(key)
filtered = []
for token in doc:
    if token.is_punct or token.is_stop:
        continue
    filtered.append(token.lemma_)

In [133]:
filtered

['Human', 'Resources', 'HR']

In [109]:
data["vector"]= data["job_title"].apply(lambda x: preprocess_and_vectorize(x))

In [110]:
key="Human Resources HR"

In [111]:
key_ward=preprocess_and_vectorize(key)

In [112]:
cosin_sim = []
for i in range(job_title.shape[0]):
    sim = cosine_similarity(data["vector"][i].reshape(1, -1),key_ward.reshape(1, -1))
    cosin_sim.append(sim)


In [113]:
data["similarity"]=cosin_sim

In [119]:
data

id                                          job_title  \
0      1  2019 C.T. Bauer College of Business Graduate (...   
1      2  Native English Teacher at EPIK (English Progra...   
2      3              Aspiring Human Resources Professional   
3      4             People Development Coordinator at Ryan   
4      5    Advisory Board Member at Celal Bayar University   
..   ...                                                ...   
99   100  Aspiring Human Resources Manager | Graduating ...   
100  101              Human Resources Generalist at Loparex   
101  102   Business Intelligence and Analytics at Travelers   
102  103                     Always set them up for Success   
103  104   Director Of Administration at Excellence Logging   

                                location connection  fit  \
0                         Houston, Texas         85    1   
1                                 Kanada      500+     0   
2    Raleigh-Durham, North Carolina Area         44    1   
3                          Denton, Texas      500+     0   
4                         İzmir, Türkiye      500+     0   
..                                   ...        ...  ...   
99              Cape Girardeau, Missouri        103    1   
100  Raleigh-Durham, North Carolina Area      500+     1   
101           Greater New York City Area         49    1   
102             Greater Los Angeles Area      500+     0   
103                          Katy, Texas      500+     0   

                                                vector      similarity  
0    [-0.02120758, -1.6550734, 0.9576593, 0.9891001...   [[0.6072153]]  
1    [-1.3577785, -2.4673958, 1.4322058, 1.3633429,...   [[0.3882938]]  
2    [-1.121565, -1.5824499, 0.89269996, -0.6570975...   [[0.7653773]]  
3    [-1.4700725, -0.962675, 0.8306445, 1.102165, -...  [[0.55128133]]  
4    [-2.5489342, -0.39851665, 2.6469526, 0.4085733...  [[0.42609465]]  
..                                                 ...             ...  
99   [0.43837935, -4.067801, 2.8288026, 1.1667663, ...   [[0.6048552]]  
100  [-2.2978, -1.700545, 0.934045, 0.4249525, 0.63...   [[0.7184749]]  
101  [0.13548999, -0.8079925, 0.8790801, 1.7319751,...   [[0.6309317]]  
102  [-2.80491, 1.080565, -1.296145, 0.328225, 0.91...  [[0.16266294]]  
103  [0.2996375, -3.663, 2.3311825, 1.9852725, 0.18...   [[0.5883906]]  

[104 rows x 7 columns]

In [100]:
data['fit'] = data['similarity'].apply(lambda x: 1 if x >= 0.6 else 0)

In [120]:
x_train,x_test,y_train,y_test = train_test_split(data.vector, data.fit, test_size=0.20, random_state=seed)

In [121]:
x_train

82    [0.083848305, -1.0936135, 1.1138532, 1.3832684...
66    [-0.51526195, -1.11868, 0.113520026, 0.551174,...
44    [-1.3577785, -2.4673958, 1.4322058, 1.3633429,...
42    [-1.6860334, -1.4231333, 0.82883, 0.4365183, 1...
40    [-0.21705396, -1.3085687, 0.7400333, 0.12965, ...
                            ...                        
75    [0.52815914, -1.7491531, -0.9956584, -1.033295...
9     [-1.0868, -0.6150333, 0.2142684, 1.374375, 2.2...
72    [-0.27208126, -1.006295, 0.3883125, -0.779805,...
12    [-1.6860334, -1.4231333, 0.82883, 0.4365183, 1...
37    [1.1505734, -2.2, 1.95001, 1.8100666, 0.996463...
Name: vector, Length: 83, dtype: object

In [122]:
x_train_2d= np.stack(x_train)
x_test_2d=np.stack(x_test)

In [123]:
x_train_2d

array([[ 0.08384831, -1.0936135 ,  1.1138532 , ..., -2.9220102 ,
        -0.5548433 ,  3.3456383 ],
       [-0.51526195, -1.11868   ,  0.11352003, ..., -3.8870778 ,
         0.08165202,  2.1212866 ],
       [-1.3577785 , -2.4673958 ,  1.4322058 , ..., -1.6298573 ,
        -1.894428  ,  2.6255171 ],
       ...,
       [-0.27208126, -1.006295  ,  0.3883125 , ..., -3.4265542 ,
         0.25727627,  1.3980795 ],
       [-1.6860334 , -1.4231333 ,  0.82883   , ..., -3.47159   ,
         0.39238492,  0.4536178 ],
       [ 1.1505734 , -2.2       ,  1.95001   , ..., -4.812267  ,
         2.2172    ,  5.320667  ]], dtype=float32)

In [124]:
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(x_train_2d,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [125]:
y_red=model.predict(x_test_2d)

In [126]:
print(classification_report(y_red,y_test))

              precision    recall  f1-score   support

           0       0.78      1.00      0.88         7
           1       1.00      0.86      0.92        14

    accuracy                           0.90        21
   macro avg       0.89      0.93      0.90        21
weighted avg       0.93      0.90      0.91        21



In [127]:
model_2 = RandomForestClassifier()
model_2.fit(x_train_2d,y_train)

RandomForestClassifier()

In [129]:
y_red=model_2.predict(x_test_2d)
print(classification_report(y_red,y_test))

              precision    recall  f1-score   support

           0       0.89      1.00      0.94         8
           1       1.00      0.92      0.96        13

    accuracy                           0.95        21
   macro avg       0.94      0.96      0.95        21
weighted avg       0.96      0.95      0.95        21



# Re-ranking

In [194]:
ranked_candidates = data.sort_values(by='similarity', ascending=False)

In [195]:
ranked_candidates

id                                          job_title  \
52    53  Seeking Human Resources HRIS and Generalist Po...   
61    62  Seeking Human Resources HRIS and Generalist Po...   
39    40  Seeking Human Resources HRIS and Generalist Po...   
9     10  Seeking Human Resources HRIS and Generalist Po...   
7      8                               HR Senior Specialist   
..   ...                                                ...   
10    11                      Student at Chapman University   
62    63                      Student at Chapman University   
40    41                      Student at Chapman University   
97    98                                            Student   
102  103                     Always set them up for Success   

                      location connection  fit  \
52   Greater Philadelphia Area      500+     1   
61   Greater Philadelphia Area      500+     1   
39   Greater Philadelphia Area      500+     1   
9    Greater Philadelphia Area      500+     1   
7       San Francisco Bay Area      500+     1   
..                         ...        ...  ...   
10     Lake Forest, California          2    0   
62     Lake Forest, California          2    0   
40     Lake Forest, California          2    0   
97         Houston, Texas Area          4    0   
102   Greater Los Angeles Area      500+     0   

                                                vector      similarity  
52   [-1.0868, -0.6150333, 0.2142684, 1.374375, 2.2...  [[0.89972734]]  
61   [-1.0868, -0.6150333, 0.2142684, 1.374375, 2.2...  [[0.89972734]]  
39   [-1.0868, -0.6150333, 0.2142684, 1.374375, 2.2...  [[0.89972734]]  
9    [-1.0868, -0.6150333, 0.2142684, 1.374375, 2.2...  [[0.89972734]]  
7    [1.1505734, -2.2, 1.95001, 1.8100666, 0.996463...  [[0.85866195]]  
..                                                 ...             ...  
10   [-0.21705396, -1.3085687, 0.7400333, 0.12965, ...  [[0.36025453]]  
62   [-0.21705396, -1.3085687, 0.7400333, 0.12965, ...  [[0.36025453]]  
40   [-0.21705396, -1.3085687, 0.7400333, 0.12965, ...  [[0.36025453]]  
97   [2.1085, 0.092194, -3.1865, -1.8936, 3.1295, 1...  [[0.33863744]]  
102  [-2.80491, 1.080565, -1.296145, 0.328225, 0.91...  [[0.16266294]]  

[104 rows x 7 columns]

In [196]:
starred_candidate_index = 7  # Index of the starred candidate
starred_candidate_fitness = ranked_candidates['similarity'][starred_candidate_index]
ranked_candidates['similarity'] = ranked_candidates['similarity'].apply(lambda x: x + .1 if x == ranked_candidates['similarity'][starred_candidate_index] else x)
re_ranked_candidates = ranked_candidates.sort_values(by='similarity', ascending=False)


In [197]:
starred_candidate_fitness

array([[0.85866195]], dtype=float32)

In [198]:
re_ranked_candidates

id                       job_title                  location connection  \
25    26            HR Senior Specialist    San Francisco Bay Area      500+    
60    61            HR Senior Specialist    San Francisco Bay Area      500+    
50    51            HR Senior Specialist    San Francisco Bay Area      500+    
7      8            HR Senior Specialist    San Francisco Bay Area      500+    
37    38            HR Senior Specialist    San Francisco Bay Area      500+    
..   ...                             ...                       ...        ...   
10    11   Student at Chapman University   Lake Forest, California          2   
62    63   Student at Chapman University   Lake Forest, California          2   
40    41   Student at Chapman University   Lake Forest, California          2   
97    98                         Student       Houston, Texas Area          4   
102  103  Always set them up for Success  Greater Los Angeles Area      500+    

     fit                                             vector      similarity  
25     1  [1.1505734, -2.2, 1.95001, 1.8100666, 0.996463...    [[0.958662]]  
60     1  [1.1505734, -2.2, 1.95001, 1.8100666, 0.996463...    [[0.958662]]  
50     1  [1.1505734, -2.2, 1.95001, 1.8100666, 0.996463...    [[0.958662]]  
7      1  [1.1505734, -2.2, 1.95001, 1.8100666, 0.996463...    [[0.958662]]  
37     1  [1.1505734, -2.2, 1.95001, 1.8100666, 0.996463...    [[0.958662]]  
..   ...                                                ...             ...  
10     0  [-0.21705396, -1.3085687, 0.7400333, 0.12965, ...  [[0.36025453]]  
62     0  [-0.21705396, -1.3085687, 0.7400333, 0.12965, ...  [[0.36025453]]  
40     0  [-0.21705396, -1.3085687, 0.7400333, 0.12965, ...  [[0.36025453]]  
97     0  [2.1085, 0.092194, -3.1865, -1.8936, 3.1295, 1...  [[0.33863744]]  
102    0  [-2.80491, 1.080565, -1.296145, 0.328225, 0.91...  [[0.16266294]]  

[104 rows x 7 columns]